### ISSUE TITLE
Support for MacOs Apple Silicon

### ISSUE THREAD

**Issue by akatecker** [creatoy/hid-gd#1]
Unfortunately I cannot use your Plugin on my M1 Macbook as the release only includes the MacOs.x86_64 but no MacOs.arm64 version. Maybe you could also compile it for this architecture?
Best regards

**Comment by creatoy** [comment]
> Unfortunately I cannot use your Plugin on my M1 Macbook as the release only includes the MacOs.x86_64 but no MacOs.arm64 version. Maybe you could also compile it for this architecture? Best regards

Sorry, I cannot compile the plugin for you because I don't have a MacOS machine. My attempt to compile with github actions also failed. So you may need to download this repository and compile it yourself, which is quite simple.

**Comment by akatecker** [comment]
Thank you for your quick reply. I never used / or compiled rust, but in the end it was as easy as you mentioned. Now your HID/GD extension works perfectly on my M1 Mac, I really appreciate your work! 
I will include the compiled arm64 library files in case you want to include them in your release. 

Very best regards
[Hid_gd_0.3_Macos_arm64.zip](https://github.com/creatoy/hid-gd/files/13660173/Hid_gd_0.3_Macos_arm64.zip)

**Comment by creatoy** [comment]
Hey,
I re-compiled an extention of the arm64 architecture using github actions, would you like to test if it workes? I couldn't test it because I don't have a MacOS machine.
You can download it from the [release page](https://github.com/creatoy/hid-gd/releases/tag/v0.1.0).

**Comment by akatecker** [comment]
Sure, it’s the least I can do. I does not work out of the box, I had to change the hid.gdextension file to: 

(…)
[libraries]
macos.arm64 = "bin/libhid_ext.macos.aarch64.release.dylib"

After this change, the extension loads without problems and list_devices / read works (did not need more for my use case which is to read from a legacy hardware device). I am running on a M1 MacBook Air 2020 with macOs Sonoma 14.0, my Godot version is 4.2 stable. 

All the best and thank you again.

> Am 18.12.2023 um 09:14 schrieb creatoy ***@***.***>:
> 
> Hey,
> I re-compiled an extention of the arm64 architecture using github actions, would you like to test if it workes? I couldn't test it because I don't have a MacOS machine.
> You can download it from the release page <https://github.com/creatoy/hid-gd/releases/tag/v0.1.0>.

**Comment by creatoy** [comment]
> I had to change the hid.gdextension file to:
(…) 
[libraries]
macos.arm64 = "bin/libhid_ext.macos.aarch64.release.dylib"

Thanks for the feedback, I will fix the mistake.
